root: true
parserOptions:
  parser: babel-eslint
env:
  browser: true
  node: true
  jest: true
extends:
- standard
- plugin:vue/recommended
plugins:
- jest
- vue
rules:
  arrow-parens: 0
  generator-star-spacing: 0
  no-console: 2
globals:
  jest/globals: true
  jasmine: true
